language: objective-c
osx_image: xcode7.3
env:
  global:
    - LC_CTYPE=en_US.UTF-8
install:
  - gem update fastlane --no-ri --no-rdoc --no-document
script:
  - ./FastlaneBox/fastlane/travis.sh
notifications:
  email: false
