# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
require "yaml"

fastlane_version "1.102.0"

default_platform :ios

CONF = YAML.load_file('conf.yml')

platform :ios do
  before_all do
    ENV["SLACK_URL"] = CONF["slack"]["webhookurl"]
  end

  desc 'Custom action'
  lane :my_action do
    sample
  end

  desc 'Analyze codes'
  desc 'This may comment to pull request'
  lane :lint do
    swiftlint
  end

  desc "Runs synx to folderize the Xcode project"
  lane :sync do
    synx
  end

  desc "Runs all the unit and ui tests"
  lane :test do
    # cocoapods
    # cathage
    if is_ci
      scan(skip_slack: false)
    else
      scan
    end
  end

  desc "Creates new screenshots and uploads them to iTunes Connect"
  lane :screens do
    snapshot
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful
    slack(message: "Successfully")
  end

  error do |lane, exception|
    slack(
      message: exception.message,
      success: false
    )
  end
end
